#!/bin/bash
yaourt -S i3-gaps-git \
          rxvt-unicode-better-wheel-scrolling \
          discord-canary \
          obs-studio-git \
          otf-hermit \
          polybar-git \
          sc-controller-git \
          spotify \
          ttf-ms-fonts \

